### ISSUE TITLE
New View: Professor Profile

### ISSUE THREAD

**Issue by curtisupshall** [SENG-499-Company-3/frontend#21]
# Description
As a professor, I'd like to be able to view a highlevel overview of my scheduling and account preferences on a profile page when I log into the application

# Acceptance Criteria

## Scenario 1: Professor sign-in
 - **GIVEN** I log into the application
 - **THEN** I should arrive at my profile upon successfully signing in

## Scenario 2: Professor has not completed their preferences form
 - **GIVEN** I have not filled in my preferences yet
 - **WHEN** I arrive at my profile
 - **THEN** some sort of reminder to complete my preferences form should be shown on my profile
 - **AND** it should include some kind of link to take me to the preferences form

## Scenario 3: Profile details
 - **GIVEN** I arrive at my profile
 - **THEN** I should see a collection of profile details, including
   - Display name, email, account type
   - Preference details for each of the classes they intend to teach
   - **TBD.**

**Comment by SlaterRGordon** [comment]
You can merge my branch for issue #25 as a starting point. It has basic template for a profile page.

**Comment by samllai** [comment]
Professor's reminder banner created on branch extending #25 . Expected to continue Preferences information in tickets #38 and #39
